### ISSUE TITLE
empty graph area

### ISSUE THREAD

**Issue by CaptainSkywave** [overhold-org/Overhold-Wallet#6] opened 2018-11-12 05:13 UTC
This is how it looks on a Windows Server 2012 R2:

![overhold](https://user-images.githubusercontent.com/8870171/48327973-091e2280-e642-11e8-8b27-5fbf8c1c5aba.png)

**Comment by blag0j** [comment] 2018-11-12 09:07
Hi @CaptainSkywave could you give us more info about the issue? As from the image we can see that the graph is shown normally - that's the intended behavior.

**Comment by CaptainSkywave** [comment] 2018-11-12 09:13
..but, from the overhold.org site I see the image of the graph area showing this:
![overhold2](https://user-images.githubusercontent.com/8870171/48337529-79896b80-e663-11e8-8250-ea43e8100d6e.png)

**Comment by CaptainSkywave** [comment] 2018-11-12 09:15
..on my first image (from the WIN Server 2012 R2 you see no graph displayed in the empty blue'ish area

**Comment by blag0j** [comment] 2018-11-12 10:46
@CaptainSkywave, that's because the parameters are set to HOURLY which means the graph data from the latest hour is shown for the cryptocurrency, meaning that there are not many changes (as it can be observed from the chart).  The photo from the overhold.org is an example chart photo, which was taken more than a year ago (you can see from the bitcoin price), and also there were many changes by then, including removing the 7 day chart interval and changing to hourly, daily and monthly data view.

I am closing this issue, because it is actually not a bug but an intended behavior.

**Closed by blag0j** 2018-11-12 10:46 UTC
