### ISSUE TITLE
Settings - Coins, current state always 'On'

### ISSUE THREAD

**Issue by riceCubes** [overhold-org/Overhold-Wallet#5] opened 2018-11-10 20:26 UTC
OS: Windows 10 (64-bit)

Under Settings > Coins, toggle UI does not save the current state, always displays 'on' for all coins.

Omni toggle 'Off' also toggles Litecoin to 'Off'.
- Doesn't affect Litecoin display state in Home and Addresses (still displayed)

Coins missing from display UI in Home and Address after toggling 'Off', then 'On':
- Omni, Counterparty, Maid

**Comment by blag0j** [comment] 2018-11-11 10:12
@riceCubes, thanks for the bug report and the description, but please provide us more info - following our [contribution guide](https://github.com/overhold-org/Overhold-Wallet/blob/master/CONTRIBUTING.md).

Currently Omni, Counterparty and only available in explorer view, so they are not available on the Home page, as well as on the Addresses page.

We will take a look and get back to you.

**Comment by blag0j** [comment] 2018-11-11 16:30
@riceCubes I can confirm that there is visual bug:

When you toggle Omni 'Off' it also toggles Litecoin to 'Off', but the functionality is preserved (Litecoin is not switched off and still displayed on the wallet - Addresses, Prices, etc.). About the rest of the stuff, we couldn't reproduce any of that.

We are working on fixing this bug, and will update you and this issue once it is fixed.

**Comment by riceCubes** [comment] 2018-11-12 07:44
@blag0j There is a similar visual bug for Maid and Omni.  When both are 'Off' and toggle Maid to 'On', Omni will also toggle.

My wallet is now preserving the coin states as expected - not sure what changed from when I first made the issue.  If I encounter it again, I'll update  here again.

**Comment by blag0j** [comment] 2018-11-12 09:51
@riceCubes great, the wallet probably had some issues while stabilizing the first time.

About Maid and Omni, thanks for reporting, but it is not a visual bug - it is intended to be that way, because Maid is token running on Omni blockchain and also it uses Omni's APIs to fetch data, so it is natural for Omni to be set to on when the Maid is set to on because in some way Maid is dependent on Omni.

**Comment by blag0j** [comment] 2018-11-27 14:46
@riceCubes This issue has been fixed with the latest updates in the develop branch. The release will be published in the following days.

**Closed by blag0j** 2018-11-27 14:46 UTC
Labels: UI bug
